name: links
version: 1.0.0
description: Links Plugin for PolymorphicBot
dependencies:
  html5lib: '>=0.12.0 <0.13.0'
  http: '>=0.11.1+1 <0.12.0'
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
