name: links
version: 1.0.0
description: Links Plugin for PolymorphicBot
dependencies:
  html5lib: '>=0.12.0 <0.13.0'
  http: '>=0.11.1+1 <0.12.0'
  irc: '>=1.4.2 <1.4.6'
  plugins:
    git: git://github.com/samrg472/plugins.dart.git
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
